---
title: "Formatieve opdracht RNA-seq"
author: "Mathijs van Drongelen(1832719), Diana Tereshchenko(1865053)"
date: "`r Sys.Date()`"
output: html_document
---

```{r, setup}
knitr::opts_chunk$set(
  echo = TRUE, 
  message = FALSE, 
  warning = FALSE) 

#Libraries 

library(tidyverse)
library(Rsubread)
library(DESeq2)
library(pheatmap)
library(AnnotationDbi)
library(org.Hs.eg.db)
library(GOstats)
```
# Onderdeel Les 1 
## Onderdeel 1a
- *Schrijf een korte introductie voor de Rmarkdown met daarin in eigen woorden het doel van jouw onderzoek/analyses.*

Deze formatieve opdracht is gebaseerd op onderzoek naar fibroblasten afkomstig van de menselijke huid en daaruit geïnduceerde pluripotente stamcellen(iPSC). Van de twee proefpersonen zijn er twee cellijnen verkregen. De vier transcriptiefactoren, namelijk MYC, OCT3/4, SOX2 en KLF4, worden tot overexpressie gebracht om iPSC te maken. 

Voor elke conditie zijn twee RNA-seq-datasets met paired reads gegenereerd. Voor het genereren van deze RNA-seq-datasets is het standed protocol gebruikt, waarmee plus- en min-strengen kunnen worden geïdentificeerd. 

In de eerste deel van de formatieve opdracht worden volgende analyses uitgevoerd:

- Kwaliteitscontrole op basis van FastQC-rapporten (1c)

- De alignment van de RNA-seq-datasets met gebruik van hg38 genome index (1d)

- Visuele inspectie van de aligment statistiek (1e)

## Opdracht 1b:
- *Stel dat de sample identifiers in een textfile staan. Schrijf een bash script voor het downloaden van de fastq files voor alle identifiers. Zorg ervoor dat dit script een for loop bevat, zodat je niet voor elke fastq file een aparte regel code hoeft te schrijven.*

```{bash, opdr1b, eval = FALSE}
for id in $(cat "$text.txt")
do 
    fastq-dump --split-3 --outdir "$outdirsra" --gzip "$id"
done
```

## Onderdeel 1c
- *Bekijk de FastQC html rapporten voor de verschillende fastq files. Wat zijn je conclusies?*
Samenvatting van de resultaten uit de FastQC html rapporten: 

- per base sequence quality: >30  = Goed 
- per sequence quality scores: piek aan de rechterkant van de grafiek, hoge gemiddelde Phred-score = Goed 

Conclusie: De kwaliteit van de sequencing data is in alle rapporten acceptabel en geschikt voor downstream-analyse.

## Onderdeel 1d
- *Schrijf code voor het uitvoeren van de alignment met de Rsubread package. Voor de alignment kun je gebruik maken van de hg38 genome index die is te vinden /home/daur2/rnaseq/hg38_index/*

- *NB: voer dit script niet uit, want de alignment is al voor jullie uitgevoerd!*

# dubbelcheck deze code op directories!

```{R, opdr1d, eval = FALSE}
# Create object with location of fastq files
fastq_dir <- "/home/daur2/rnaseq/rnaseq_ipsc/fastq/"

# Create object with basename of index files
hg38_index <- "/hg38_index/hg38_index"

# Create object with output dir for bam files
bam_dir <- "~/daur2/bam/"

# Create a vector with sample numbers
samples <- list.files(fastq_dir, pattern = "_[12].fastq.gz") %>% 
  str_remove(pattern = "_[12].fastq.gz") %>%
  unique()

# Align the reads in the fastq files
alignment_statistics <- align(
  
  index = hg38_index,
  readfile1 = paste0(fastq_dir, samples, "_1.fastq.gz"), 
  readfile2 = paste0(fastq_dir, samples, "_2.fastq.gz"),
  type = "rna", input_format = "gzFASTQ", output_format = "BAM",
  output_file = paste0(bam_dir, samples, ".bam"), 
      
  # report only uniquely mapping reads
  unique = TRUE,
      
  # number of CPU threads
  nthreads = 10
      
)

# Store the alignment statistics as R object
saveRDS(alignment_statistics, file = paste0(bam_dir, "alignment_statistics.rds"))
```

## Onderdeel 1e
- *In de directory met de bam files kun je ook het bestand ‘alignment_statistics.rds’ vinden. Gebruik dit bestand om een grouped bar graph te maken met daarin voor elk sample zowel het percentage mapped fragments als het percentage unmapped fragments.*

```{R, opdr1e}
#Step 1 RDS to tibble 
Alignment<-readRDS(file = "alignment_statistics.rds") %>% t() %>% as_tibble()
alignment_statistics<-readRDS("alignment_statistics.rds")

#Step 2 add columns
Alignment<-Alignment %>%
  mutate(Naam = colnames(alignment_statistics), .before = Total_fragments,
         mapped_perct = Mapped_fragments/Total_fragments*100, 
unmapped_perct = Unmapped_fragments/Total_fragments*100)

#Step 3 make data tidy for barplot 
Alignment<-Alignment %>% pivot_longer(cols = c("mapped_perct", "unmapped_perct"), 
                           names_to = "mapping", values_to = "percentage")

#Step 4 plot the data
Alignment %>% ggplot(aes(x = percentage, y = Naam, fill = mapping))+
  geom_col(position = position_dodge())+
  labs(title = "Percentage of mapped and unmapped areas in the RNA sequences",
       x = "Percentage (%)", y = "Name of SRR Identifier")

```

- *Wat is je conclusie op basis van deze grafiek?*

Conclusie: Ongeveer 95% van de RNA sequenties zijn mapped en 5% is unmapped. Er zijn veel 
unieke reads die plekken matchen met de reference genome 
en weinig die nergens goed kunnen matchen.


# Onderdeel Les 2 

## Onderdeel 2a

- *Schrijf code voor het genereren van de count table met de Rsubread package.*

- *NB: voer dit script niet uit, want de count table is al voor jullie gegenereerd!*

```{R, opdr2a, eval = FALSE}
#input .bam file location
bam_dir <- "/home/daur2/rnaseq/rnaseq_ipsc/bam/"

#output counts location
counts_dir <- "/home/daur2/rnaseq/rnaseq_ipsc/counts/"

# Create vector with names of bam files for files argument of Featurecounts
bam_files <- list.files(bam_dir, pattern = ".*\\.bam$", full.names = TRUE)

# Count the reads per gene using the in-built NCBI RefSeq annotations
read_counts <- featureCounts(
  
  files = bam_files,
  annot.inbuilt = "hg38",  #we use human genome 
  useMetaFeatures = TRUE,
  strandSpecific = 0,
  isPairedEnd = TRUE,  #data is Paired (forward en reverse fragment)
  countReadPairs = TRUE, #tel data als paar aka een DNA fragment ipv. forward en reverse individueel 
  nthreads = 10
)

```

## Onderdeel 2b 

- *Gebruik de ‘stat’ data frame uit de count table om een staafdiagram te maken met daarin het percentage assigned reads voor elk sample.*


```{R, opdr2b}
Counting_table_raw<-readRDS("/home/daur2/rnaseq/rnaseq_ipsc/counts/read_counts.rds")
counting_table<-Counting_table_raw$stat
rownames(counting_table) <- counting_table$Status
counting_table$Status = NULL

counting_table_t<-counting_table %>% t() %>% 
  as_tibble()

 counting_table_t<-counting_table_t %>% 
   mutate(Names=colnames(counting_table)) %>%
  mutate(Total=colSums(counting_table)) %>% 
  mutate(Assign_prct=Assigned/Total*100)
 
counting_table_t %>% ggplot(aes(x = Names, y = Assign_prct))+
  geom_col()+
  labs(title = "Percentage of assigned reads from total reads in RNA-seq samples",
       x = "RNA-seq samples",
       y = "Assigned read (%)")+
  theme(axis.text.x = element_text(angle = 90))
```

- *Wat is je conclusie op basis van deze grafiek?*

Conclusie: Het percentage assigned reads van de totale reads is 40-60%. Is hoger
in de eerste 4 samples vergeleken met de laatste 4. De iPSCs lijken gemiddeld minder assigned
reads te hebben dan de fibroblast cellen. 

## Onderdeel 2c 

- *Gebruik de count table en het csv bestand met sample informatie om een DESeq2 object te maken.*

```{R, opdr2c}
# Obtain the count matrix
count_matrix <- Counting_table_raw$counts
metadata <- read_csv("/home/daur2/rnaseq/rnaseq_ipsc/ipsc_sampledata.csv")

# Convert the metadata to data frame object
metadata <- as.data.frame(metadata)

# Add rownames to the metadata data frame
rownames(metadata) <- paste0(metadata$Run, ".bam")

# Check if column names of count table are the same as row names of metadata object
colnames(count_matrix) == rownames(metadata)

#Factor Cell types as the difference in celltype / treatment to iPSC's is the point
# of interest

metadata$Cell_type<-metadata$Cell_type %>% str_replace("Skin derived fibroblast", "Skin_derived_fibroblast")

metadata$Cell_type <- metadata$Cell_type %>% 
factor(levels = c("Skin_derived_fibroblast", "iPSC"))


# Create the DESeqDataSet object
dds <- DESeqDataSetFromMatrix(
  countData = count_matrix,
  colData = metadata, 
  design = ~ Cell_type
)

```

## Onderdeel 2d 
- *Voer een PCA analyse uit en maak een plot van PC1 versus PC2.* 

```{R, opdr2d}
# log2 normalization 
dds_normalized <- rlog(dds)

# Perform PCA 
pca <- dds_normalized %>% assay() %>% t() %>% prcomp()

# Find the proportion of variance explained by each PC
pca_summary <- summary(pca)$importance
pca_summary

# Create data frame with metadata and the PCA values for plotting
pca_plotting <- cbind(metadata, pca$x) %>% mutate(source_name = str_remove_all(source_name, "Fibroblast |iPSC ")) %>%
  mutate(Cell_type = str_replace_all(Cell_type, "Skin_derived_fibroblast", "Skin derived fibroblasts")) 
colnames(pca_plotting)
pca_plotting
# Obtain the percentages of variation covered by PC1 and PC2
PC1_var <- round(pca_summary["Proportion of Variance", "PC1"]*100, digits = 1)
PC2_var <- round(pca_summary["Proportion of Variance", "PC2"]*100, digits = 1)
# Plot PC1 vs PC2
ggplot(pca_plotting) + 
  geom_point(aes(x=PC1, y=PC2, color = Cell_type, shape = source_name ), size = 5) +
  ggtitle("PCA voor iPS") +
  xlab(paste0("PC1 (", PC1_var, "%)")) +
  ylab(paste0("PC2 (", PC2_var, "%)")) +
  labs(color = "Cell type",
       shape = "Source name"
  ) +
  theme_bw()

```

- *Wat is je conclusie op basis van deze plot?*
Conclusie: PC1 verklaart 82,2% van de variatie in de gegevens, wat het grootste deel van de totale variatie omvat. PC1 scheidt de celtypen duidelijk van elkaar, met fibroblasten aan de linkerkant en iPSC’s aan de rechterkant. Dit geeft aan dat het celtype de belangrijkste oorzaak van variatie is.

Fibroblasten vertonen grotere scheiding langs PC2, wat wijst op grotere variabiliteit binnen de groep in vergelijking met iPSC. Maar dit vertegenwoordigt een veel kleiner deel van de totale variatie.

## Onderdeel 2e

- *Maak een heatmap waarin de correlatiecoëfficiënten voor de verschillende samples zijn weergegeven.*

```{R, opdr2e}
# Extract the matrix from the normalized DESeq object
dds_normalized_matrix <- assay(dds_normalized)    

# Compute pairwise correlation values
fib_ipsc_cor <- cor(dds_normalized_matrix)    
fib_ipsc_cor

# Plot heatmap using the correlation; annotate the heatmap based on the cell type
pheatmap(fib_ipsc_cor, annotation = metadata["Cell_type"])
```

- *Wat is je conclusie op basis van deze heatmap?* 
Conclusie: Ook in de heatmap worden monsters gegroepeerd op basis van het celtype. 
De heatmap ondersteunt de resultaten van de PCA. iPSCs lijken meer op elkaar dan op
fibroblasten en vice versa. 

Er is een groter verschil tussen iPSC en fibroblasten dan gelijksoortige cellen.


# Onderdeel Les 3 

## Onderdeel 3a

- *Voer de DGE analyse uit met behulp van DESeq2. Hoeveel genen zijn er upgereguleerd (adjusted p-value < 0.05 en LFC > 1)? En hoeveel genen zijn er downgereguleerd (adjusted p-value < 0.05 en LFC < -1)?*

```{R, opdr3a}
# Perform the DGE analysis using DESeq2
ipsc_dge <- DESeq(dds)
# Obtain the results for the DGE analysis
ipsc_dge_results <- results(ipsc_dge, alpha = 0.05, lfcThreshold = 1)
summary(ipsc_dge_results)
```
- *Vergelijk de aantallen met de aantallen voor de airway studie. Wat is je conclusie?*

Resultaten van airway studie:
out of 21507 with nonzero total read count
adjusted p-value < 0.1
LFC > 0 (up)       : 1897, 8.8%
LFC < 0 (down)     : 1542, 7.2%
outliers [1]       : 43, 0.2%
low counts [2]     : 5329, 25%

Voor de iPSC vs fibroblast studie waren er 3450 upgereguleerde genen en 
2638 downgereguleerde genen. 

Zelfs met een lagere p-cutoff van 0.05 vs 0.1 in de airway studie, 
heeft de iPSC vs. fibroblast studie een hoger percentage genen met een |LFC| > 1. 
Er zijn dus meer verschillen in DGE tussen iPSCs en fibroblasten dan tussen
Airway smooth mucle cells (ASMs) voor en na behandeling met 1µM dexamethasone.

## Onderdeel 3b
- *Create a Volcano plot in which you colour all genes with an adjusted p-value < 0.05 and |LFC|>1 darkblue. Also indicate the LFC and p-value thresholds as dashed lines in the plot.*

```{R, opdr3b}
# Create a data frame for plotting without genes with padj = NA
ipsc_dge_plotting <- data.frame(ipsc_dge_results) %>% filter(!is.na(padj))

# Create column specifying if gene is significantly differentially expressed
ipsc_dge_plotting <- ipsc_dge_plotting %>% 
  mutate(signif = if_else(padj < 0.05 & abs(log2FoldChange) > 1, 
                          "Significant", "Not significant"))


#Obtain the id of the most significantly upregulated gene
significant_genes <- ipsc_dge_results[which(ipsc_dge_results$padj < 0.05),]
topGene <- significant_genes[which.max(significant_genes$log2FoldChange),]
topGene_name <- rownames(topGene)
topGene_name

#Obtain the id of the most signigicantly downregulated gene
topGene_down <- significant_genes[which.min(significant_genes$log2FoldChange),]
topGene_down_name <- rownames(topGene_down)
topGene_down_name

#
# Create a volcano plot
ipsc_dge_plotting %>% 
  ggplot(aes(x = log2FoldChange, y = -log10(padj), color = signif)) +
  geom_point() + 
  xlab("log2 fold change") +
  ylab("-log10 adjusted p-value") + 
  theme_minimal() +
  
  # Change the legend text and the colours
  scale_colour_manual(values = c("grey", "darkblue"), name = "Significance") +
  
  
  # Indicate thresholds as lines
  geom_hline(yintercept = -log10(0.01), linetype = "dashed") +
  geom_vline(xintercept = 1, linetype = "dashed") +
  geom_vline(xintercept = -1, linetype = "dashed") +
  
    # Annotate the most significantly upregulated gene
  annotate("text", x = topGene$log2FoldChange, y = -log10(topGene$padj)*0.8, 
           label = topGene_name, colour = "blue", size = 2, vjust = -2) +
  annotate("text", x = topGene_down$log2FoldChange, y = -log10(topGene_down$padj)*0.8, 
           label = topGene_down_name, colour = "blue", size = 2, vjust = -2) 
```

## Onderdeel 3c
- *Maak een heatmap met daarin de count values voor de 15 significante DE genen (adjusted p-waarde < 0.05) met de grootste |LFC|.*'

```{R, opdr3c}

significant_genes <- ipsc_dge_results[which(ipsc_dge_results$padj < 0.05),]
top15_genes <- rownames(
  significant_genes[order(-abs(significant_genes$log2FoldChange)), ][1:15, ]
)

# Obtain the count values for these genes
count_values <- assay(dds)[top15_genes,]

# Replace the column names with conditions
colnames(count_values) <- colData(dds)$Cell_type

# Visualize the results in a heatmap
pheatmap(count_values, show_rownames = TRUE)
```

# Onderdeel Les 4

## Onderdeel 4a
- *Maak een heatmap zoals bij onderdeel 3c. Echter, zorg ervoor dat de rijen nu gelabeld worden met het gensymbool i.p.v. de Entrez identifier.*
```{R, opdr4a}

# Replace the column names with conditions
colnames(count_values) <- colData(dds)$Cell_type

rownames(count_values) <- mapIds(org.Hs.eg.db,
                             keys = rownames(count_values),
                             column = "SYMBOL",
                             keytype = "ENTREZID",
                             multiVals = "first")

# Visualize the results in a heatmap
pheatmap(count_values, show_rownames = TRUE)
```

## Onderdeel 4b
- *Schrijf een functie voor het uitvoeren van de GO term enrichment analyse. Deze functie heeft 4 input argumenten:*

1. *DESeq2 results object (results(DESeq(dds)))*
2. *Logische waarde (TRUE of FALSE) die aangeeft of de enrichment analyse gedaan moet worden voor de upgereguleerde genen of voor de downgereguleerde genen.*
3. *Drempelwaarde voor |LFC|.*
4. *Drempelwaarde voor adjusted p-waarde.*
- *De output van de functie is de summary van de GO term analyse  (summary(hyperGTest(test_object)))*

- *Bijvoorbeeld: gotermAnalysis(ipsc_dge_results, upregulated = FALSE, 1, 0.01) geeft de summary van de enrichment analyse voor de downgereguleerde genen met een LFC < -1 en een adjusted p-waarde < 0.01 voor de genen in het DESeq2 results object ipsc_dge_results.*

```{R, opdr4b}

#stap 1 functie argumenten voor DEseq2 results object, regulatie, lfc- en p-waarde threshold

GO_enrichment_analysis<-function(DEseq_results,upregulation,lfc_threshold,pval_threshold){
  
  all_genes1 <- DEseq_results %>% data.frame() %>% rownames()
  
  #stap 2 if-case voor upregulatie
  
  if (upregulation == TRUE){
    
    upregulated_genes1 <- DEseq_results %>% data.frame() %>% 
  filter(log2FoldChange > lfc_threshold, padj < pval_threshold) %>% rownames()
  
  
  #stap2.5 voeg output toe voor upregulatie
  
  test_object_upreg1 <- new("GOHyperGParams",
                   geneIds = upregulated_genes1,
                   universeGeneIds = all_genes1, 
                   annotation = "org.Hs.eg.db", 
                   ontology = "BP", 
                   pvalueCutoff = 1,
                   testDirection = "over")
  
  #summary object upreg
  
goterm_analysis_upreg <- (summary(hyperGTest(test_object_upreg1)))

return(goterm_analysis_upreg)
}
   #stap 3 if-case voor down regulatie
  
  else if  (upregulation == FALSE){
    
     downregulated_genes1 <- DEseq_results %>% data.frame() %>% 
  filter(log2FoldChange < -lfc_threshold, padj < pval_threshold) %>% rownames()
    
     #stap 3.5 voeg output toe voor downregulatie
     
    test_object_downreg1 <- new("GOHyperGParams",
                   geneIds = downregulated_genes1,
                   universeGeneIds = all_genes1, 
                   annotation = "org.Hs.eg.db", 
                   ontology = "BP", 
                   pvalueCutoff = 1,
                   testDirection = "over")
     
#summary object downreg
     
goterm_analysis_downreg <- (summary(hyperGTest(test_object_downreg1)))
return(goterm_analysis_downreg)
  }
}
  
# ipsc_input<-(results(DESeq(dds)))
 # indien je de functie wil testen, ipsc_dge_results werkt ook
  # GO_enrichment_analysis(ipsc_input,upregulation = FALSE,1,0.01)

```

## Onderdeel 4c

- *Voer een GO term enrichment analyse uit voor de upgereguleerde genen (gedefinieerd als adjusted p-value < 0.01 en LFC > 1) en voor de downgereguleerde genen (gedefinieerd als adjusted p-value < 0.01 en LFC < -1). Maak voor beide analyses een grafiek.*

```{R, opdr4c}

ipsc_dge_results_go <- results(ipsc_dge, alpha = 0.01, lfcThreshold = 1)

# Create a list of upregulated genes
upregulated_genes <- ipsc_dge_results_go %>% data.frame() %>% 
  filter(log2FoldChange > 1, padj < 0.01) %>% rownames()

# Create a list of downregulated genes
downregulated_genes <- ipsc_dge_results_go %>% data.frame() %>% 
  filter(log2FoldChange < -1, padj < 0.01) %>% rownames()

# Create a list of all genes in the dataset
all_genes <- ipsc_dge_results_go %>% data.frame() %>% rownames()

# Perform GO term enrichment analysis for upregulated genes 
test_object_upreg <- new("GOHyperGParams",
                   geneIds = upregulated_genes,
                   universeGeneIds = all_genes, 
                   annotation = "org.Hs.eg.db", 
                   ontology = "BP", 
                   pvalueCutoff = 1,
                   testDirection = "over")
goterm_analysis_upreg <- hyperGTest(test_object_upreg)

goterm_analysis_upreg

goterm_analysis_upreg_results <- summary(goterm_analysis_upreg)


# Perform GO term enrichment analysis for downregulated genes
test_object_downreg <- new("GOHyperGParams",
                   geneIds = downregulated_genes,
                   universeGeneIds = all_genes, 
                   annotation = "org.Hs.eg.db", 
                   ontology = "BP", 
                   pvalueCutoff = 1,
                   testDirection = "over")

goterm_analysis_downreg <- hyperGTest(test_object_downreg)

goterm_analysis_downreg

goterm_analysis_downreg_results <- summary(goterm_analysis_downreg)


#Adjust p values for multiple testing 
goterm_analysis_upreg_results$padj <- p.adjust(goterm_analysis_upreg_results$Pvalue, method = "BH")

goterm_analysis_downreg_results$padj <- p.adjust(goterm_analysis_downreg_results$Pvalue, method = "BH")

# Select only gene sets that are larger than 5 but smaller 
# than 500 (to prevent taking along very small and very large
# gene sets).
goterm_analysis_upreg_results <- goterm_analysis_upreg_results %>% filter(Count > 5) %>% filter(Count < 500)

goterm_analysis_downreg_results <- goterm_analysis_downreg_results %>% filter(Count > 5) %>% filter(Count < 500)

#Select the top 20 GO terms 
goterm_analysis_upreg_top20  <- goterm_analysis_upreg_results[order(goterm_analysis_upreg_results$padj)[1:20],]
goterm_analysis_downreg_top20 <- goterm_analysis_downreg_results[order(goterm_analysis_downreg_results$padj)[1:20],]

#Plot the p-values of the top 20 GO terms (upregulated)
p1 <- goterm_analysis_upreg_top20 %>% ggplot(aes(x = Term, y =-log10(padj))) +
  geom_point() +
  coord_flip() + 
  ylab(expression(-log[10](adjuisted ~italic(P)~value))) +
  xlab("GO terms") + 
  ggtitle("Top 20 enriched GO terms\n for upregulated genes")

p1

#Plot the p-values of the top 20 GO terms (downregulated)
p2 <- goterm_analysis_downreg_top20 %>% ggplot(aes(x = Term, y =-log10(padj))) +
  geom_point() +
  coord_flip() + 
  ylab(expression(-log[10](adjuisted ~italic(P)~value))) +
  xlab("GO terms") + 
  ggtitle("Top 20 enriched GO terms\n for downregulated genes")

p2
 

```
- *Wat zijn je conclusies? Welke processen worden er downgereguleerd tijdens de vorming van stamcellen uit fibroblasten? En welke processen worden juist upgereguleerd?*

Conclusie: Volgens de GO term enrichment analyse voor upreguleerde genen is er sprake van een sterke upregulatie van neuronale processen, zoals neurale ontwikkeling, neurogenese en neuronale differentiatie. Daarnaast zijn ook signaalroutes die verband houden met cel-celcommunicatie en synaptische functie upgereguleerd. 

GO term enrichment analyse voor downgereguleerde genen laat vooral een afname zien in vasculaire processen (ontwikkeling van het circulatiesysteem, morfogenese van bloedvaten), samen met verminderde celmotiliteit en proliferatie. 

Deze resultaten wijzen op een verschuiving in de cellulaire identiteit, waarbij cellen overgaan naar een meer neuronale fenotype. 





