
# Project Leptospira introductie

Dit project is gedeeltelijk vertrouwlijk, dus deze introductie zal gaan over de Leptospira bacterie waar wij mee te werk gaan. 

Leptospira is een bacterie, deze bacterie staat bekend als grote oorzak van zoönose.De ziekte komt vaak voor bij in tropische regio's met warm weer en slechte hygiëne. Leptsopira worden gekarakteriseerd door hun unieke vorm. De bacterien zijn dun, lang en spiraalvormig. Leptospira is erg bewegelijk is water en verspreid zijn besmetting via water. Het leptospira genoom is ~4.000.000 bp, bevat 2 tot 9 circulaire chromosomen. CI is het grote chromosoom van 3.6Mb waar de meeste genen zitten, CII is een kleiner genoom met overige essentiële genen. Er worden ook leptofagen en plasmiden gevonden in leptospira. De besmetting komt meestal voor door vervuiling van het water door besmette knaagdieren, maar huisdieren en vee kunnen ook besmet raken en direct mensen besmetten. Het grote probleem met leptospira en leptospirose is dat de grote meerderheid van patiënten naar het ziekenhuis moeten, in nederland werd 86% van de patiënten met leptospirose opgenomen in het ziekenhuis. (@costaGlobalMorbidityMortality2015; @obelsIncreasedIncidenceHuman2025; @johnsonLeptospira1996; @lehmannLeptospiralPathogenomics2014; @rajapakseLeptospirosis2025)





