---
title: "Parametrized COVID-19 data"
output: html_document
params:
  land: "France"
  jaar: "2020"
  maand: "12"
---

```{r setup, message=FALSE}
library(tidyverse)
library(stringr)
library(gridExtra)
```

```{r data acquisition, fig.width=13}
covid_data<-read.csv("https://opendata.ecdc.europa.eu/covid19/nationalcasedeath_eueea_daily_ei/csv/", na.strings = "", fileEncoding = "UTF-8-BOM")

covid_data$year<-as.factor(covid_data$year)

covid_data$cases<-abs(covid_data$cases)
covid_data$deaths<-abs(covid_data$deaths)

covid_filtered<-covid_data %>% filter(countriesAndTerritories == params$land & year == params$jaar & month == params$maand)

case_plot<-covid_filtered %>% ggplot(aes(x = day,y = cases))+
  geom_col()+
  labs(title = paste0("Number of COVID-19 cases in ",params$land," in the month of ",params$jaar,"-",params$maand," per day"),
       x = "Days of the month",
       y = "Number of cases per day",subtitle = paste0("Data was taken from European Centre for Disease Prevention and Control (ECDC). 
Total number of cases in ",params$land," during this month: ",sum(covid_filtered$cases)))+
  theme_bw()

deaths_plot<-covid_filtered %>% ggplot(aes(x = day,y = deaths))+
  geom_col()+
  labs(title = paste0("Number of COVID-19 deaths in ",params$land," in the month of ",params$jaar,"-",params$maand," per day"), x = "Days of the month",
       y = "Number of deaths per day",subtitle = paste0("Data was taken from European Centre for Disease Prevention and Control (ECDC)
Total number of deaths in ",params$land," during this month: ",sum(covid_filtered$deaths)))+
  theme_bw()
```

```{r, echo=TRUE}
case_plot
deaths_plot
```